### ISSUE TITLE
WebView??

### ISSUE THREAD

**Issue by Technologx** [bkhezry/ExtraWebView#2]
So how is this actually webview &amp; how do I link it to my site?

**Comment by bkhezry** [comment]
If your website is base on WordPress, you can use rest API and like this project, link it to app.
https://github.com/bkhezry/Jadi_Net

**Comment by Technologx** [comment]
My website is IPB based which does have rest api.

**Comment by bkhezry** [comment]
Ok, You can pass parameters of your posts to DataModel builder like Jadi_Net project.
I use retrofit2 as client for rest API.

**Comment by Technologx** [comment]
I'm not sure how to do any of that I'm new to the android coding world

**Comment by bkhezry** [comment]
I hope sample app help you :-)
